name = "A TOML Race"
date = "2023-1-15"
hours = 9

[[rankings]]
"overall place" = 1
"division place" = 1
division = "coed"
"team name" = "Awesome"
members = [
  "Alex Smith (M)",
  "Bob Turkey (M)",
  "Christine Underfoot (F)"
]

[[rankings]]
"overall place" = 2
"division place" = 2
division = "male"
"team name" = "Alright"
members = [
  "Arnold Southern (M)",
  "Bob Tripper (F)",
  "Charlie Smith (M)"
]

[[rankings]]
"overall place" = "DNF"
"division place" = "DNF"
"team name" = "Team Bad"
